/**
 * THE VERIFIED RECORD
 * ============================================================================
 * Every factual claim the site makes about Ayush Rijal lives here, and nowhere
 * else. Components read from this module; none of them contain biographical
 * strings of their own.
 *
 * That is a safety mechanism, not tidiness. M01 found V1 asserting a timeline,
 * a tech list and security work that had never been checked
 * (PROJECT_PROGRESS §9.4, K6). Funnelling every claim through one small typed
 * file makes an unverified sentence something you have to add here, on purpose,
 * rather than something that drifts into a template unnoticed.
 *
 * ── Rules ──────────────────────────────────────────────────────────────────
 * 1. Nothing enters this file that was not explicitly supplied and approved in
 *    the M03-A content session. No employers, degrees, certifications, awards,
 *    clients, metrics, dates or years of experience were supplied, so none
 *    appear — and none may be inferred from what is here.
 * 2. Statements are stored VERBATIM. They are the owner's words; rephrasing
 *    them for rhythm would make them the writer's words instead.
 * 3. If a field would need a value invented to look complete, the field does
 *    not exist. An absent fact renders as absent.
 *
 * Source: M03-A approved content, §2 of the milestone brief.
 */

export const PROFILE = {
  name: 'Ayush Rijal',

  /**
   * Primary identity, exactly as approved. Kept as parts as well as a joined
   * string so the composition can set them typographically without a component
   * ever splitting a sentence on a separator character and hoping for the best.
   */
  identity: {
    full: 'AI Developer / AI Builder · Cybersecurity Learner',
    primary: ['AI Developer', 'AI Builder'],
    secondary: 'Cybersecurity Learner',
  },

  /**
   * The core philosophy. Home renders this as four numbered stages rather than
   * as a sentence — see `PHILOSOPHY_STAGES` below, which is a presentation of
   * this exact string and must never drift from it.
   */
  philosophy: 'I build, experiment, break, and learn.',

  /** The about statement. Home sets this as its standfirst. */
  about:
    'I like building software, experimenting with AI, and understanding how systems work.',

  education: {
    level: "Bachelor's student",
    institution: 'Lincoln University',
  },

  /** Currently learning. Three subjects, no proficiency claims attached. */
  learning: ['Cybersecurity', 'AI', 'German'] as const,

  /** Core interests, in the order supplied. */
  interests: [
    'AI / LLMs',
    'Programming',
    'Cybersecurity',
    'Linux',
    'Automation',
    'Networking',
    'Hardware',
  ] as const,

  /**
   * Motivations, verbatim. NOT rendered on Home — the brief is explicit that
   * Home must not become a text wall, and these belong to the ABOUT world.
   * They are recorded here now so that when ABOUT is built there is no
   * temptation to reconstruct them from memory.
   */
  motivations: {
    programming:
      'I want to understand and build with code, rather than blindly trust code generated by AI.',
    ai: 'I explore AI because I want to understand and adopt emerging technologies, build meaningful things with them, and create a strong future in technology.',
    /**
     * Supplied in the M04 content brief §7 as "AI philosophy". Distinct from
     * `programming` above, which is about writing code; this one is about how
     * AI output is treated once it exists.
     */
    aiPhilosophy:
      "When I work with AI, I want to understand what it's doing rather than blindly accepting the output.",
    cybersecurity:
      'I love breaking things to understand how they actually work. Cybersecurity gives me a way to explore computers and systems at a deeper level while continuously developing my skills.',
    cybersecurityPhilosophy:
      'I want to understand computers deeply enough to break systems and then build them more securely.',
    ambition:
      'I want to create an impact on the world through technology and build something meaningful enough that my work is remembered.',
  },
} as const;

/**
 * `philosophy` set as a cycle rather than a sentence.
 *
 * "I build, experiment, break, and learn" describes a loop, not a list: what
 * you learn by breaking something is what you build next. Home renders it as
 * four numbered stages with a return path, in the visual language of a process
 * diagram on an engineering drawing — which is a way of *showing* the idea
 * instead of printing it as a slogan.
 *
 * The four verbs are exactly the four in `PROFILE.philosophy`, in order. The
 * glosses are descriptions of each stage, not new biographical claims.
 */
export const PHILOSOPHY_STAGES = [
  { verb: 'Build', gloss: 'Make the thing' },
  { verb: 'Experiment', gloss: 'Change one variable' },
  { verb: 'Break', gloss: 'Find where it fails' },
  { verb: 'Learn', gloss: 'Carry it into the next build' },
] as const;
